name: Github Pages Deploy

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20.0.0
      - run: npm install
      - run: npm run-script build
      - uses: docker://w9jds/firebase-action:master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
